/*
 * JSP-Tag generated by Resin-resin-3.1.15 (built Mon, 13 Oct 2014 03:54:20 PDT)
 */

package _jsp._tags;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.net.URL;

public class _include__tag extends com.caucho.jsp.java.JspTagSupport implements javax.servlet.jsp.tagext.DynamicAttributes {
  private final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;

   public URL fileURL;

  private java.lang.String page;
  private boolean _jsp_page_isSet;

  public void setPage(java.lang.String value)
  {
    this._jsp_page_isSet = true;
    this.page = value;
  }

  private java.lang.String referName;
  private boolean _jsp_referName_isSet;

  public void setReferName(java.lang.String value)
  {
    this._jsp_referName_isSet = true;
    this.referName = value;
  }

  java.util.HashMap dynParameters = new java.util.HashMap();

  public void setDynamicAttribute(String uri, String localName, Object value)
    throws javax.servlet.jsp.JspException
  {
    if (uri == null || "".equals(uri))
      dynParameters.put(localName, value);
  }

  public void doTag()
    throws javax.servlet.jsp.JspException, java.io.IOException
  {
    javax.servlet.jsp.JspContext _jsp_parentContext = getJspContext();
    com.caucho.jsp.PageContextWrapper pageContext = com.caucho.jsp.PageContextWrapper.create(_jsp_parentContext);
    setJspContext(pageContext);
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest) pageContext.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse) pageContext.getResponse();
    javax.servlet.http.HttpSession session = pageContext.getSession();
    javax.servlet.ServletContext application = pageContext.getServletContext();
    javax.servlet.ServletConfig config = pageContext.getServletConfig();
    com.caucho.jsp.PageContextWrapper jspContext = pageContext;
    javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    if (_jsp_page_isSet)
      pageContext.setAttribute("page", page);
    if (_jsp_referName_isSet)
      pageContext.setAttribute("referName", referName);
    pageContext.setAttribute("dynParameters",dynParameters);
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      
    String filePath = (String)pageContext.getAttribute("page"); //should be replaced with some mechanism of getting the name;perhaps as a request attribute
    fileURL = pageContext.getServletContext().getResource("/customview/" + filePath);

      out.write('\n');
       if(fileURL==null) {
	// cannot found orignal file
	filePath = "/coreview/" + filePath;
   } else {
	// already present jsp files
	filePath = "/customview/" + filePath;
   } 
      out.write(_jsp_string1, 0, _jsp_string1.length);
      out.print((filePath));
      out.write(_jsp_string2, 0, _jsp_string2.length);
      pageContext.include(filePath, "referName=" + com.caucho.el.Expr.toString(_caucho_expr_0.evalString(_jsp_env), null), true);
    } catch (Throwable e) {
      if (e instanceof java.io.IOException)
        throw (java.io.IOException) e;
      throw com.caucho.jsp.QJspException.createJspException(e);
    }
  }

  public javax.servlet.jsp.tagext.TagInfo _caucho_getTagInfo(javax.servlet.jsp.tagext.TagLibraryInfo taglib)
    throws com.caucho.config.ConfigException
  {
    com.caucho.jsp.cfg.TldTag tag = new com.caucho.jsp.cfg.TldTag();
    tag.setName("test");
    com.caucho.jsp.cfg.TldAttribute attr;
    attr = new com.caucho.jsp.cfg.TldAttribute();
    attr.setName("page");
    attr.setType(java.lang.String.class);
    attr.setRtexprvalue(true);
    attr.setRequired(true);
    tag.addAttribute(attr);
    attr = new com.caucho.jsp.cfg.TldAttribute();
    attr.setName("referName");
    attr.setType(java.lang.String.class);
    attr.setRtexprvalue(true);
    attr.setRequired(false);
    tag.addAttribute(attr);
    com.caucho.jsp.cfg.TldVariable var;
    return new com.caucho.jsp.java.TagInfoExt(tag.getName(),
                       getClass().getName(),
                       "scriptless",
                       "A simple tag",
                       taglib,
                       null,
                       tag.getAttributes(),
                       null,
                       null,
                       null,
                       tag.getVariables(),
                       true,
                       "dynParameters",
                       _caucho_depends);
  }

  public String _caucho_getDynamicAttributes()
  {
    return "dynParameters";
  }

  private javax.servlet.jsp.tagext.TagLibraryInfo _caucho_getTagLibrary()
    throws com.caucho.config.ConfigException
  {
    return new com.caucho.jsp.java.TagTaglib("x", "http://test.com");
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 3802963613949670813L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }
  static boolean _jsp_isTagInit;

  public void init(ServletConfig config)
    throws ServletException
  {
    if (_jsp_isTagInit)
      return;
    _jsp_isTagInit = true;
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, _caucho_getFunctionMap());
    _caucho_expr_0 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${referName}");
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("tags/include.tag"), -1366740076671709024L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }
  private static com.caucho.el.Expr _caucho_expr_0;

  private final static char []_jsp_string1;
  private final static char []_jsp_string2;
  private final static char []_jsp_string0;
  static {
    _jsp_string1 = "\n<!-- from ".toCharArray();
    _jsp_string2 = " -->\n".toCharArray();
    _jsp_string0 = "\n\n\n\n\n\n".toCharArray();
  }
}
